// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNsfrBUpALKJyQ47bVWzV5K5MQ4wtyx0w',
    appId: '1:495490506043:web:21dce2a301cb6ce6deeb1e',
    messagingSenderId: '495490506043',
    projectId: 'fir-c3d42',
    authDomain: 'fir-c3d42.firebaseapp.com',
    storageBucket: 'fir-c3d42.firebasestorage.app',
    measurementId: 'G-28QSNX9E61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqElk41aIHPbLXsYRR2v0C_cnt_-VWyw',
    appId: '1:495490506043:android:65f1039ff219913cdeeb1e',
    messagingSenderId: '495490506043',
    projectId: 'fir-c3d42',
    storageBucket: 'fir-c3d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1jGW6Emrn_AYUGjGzt6JBmcHiTShBK2s',
    appId: '1:495490506043:ios:a7c422d89117d72ddeeb1e',
    messagingSenderId: '495490506043',
    projectId: 'fir-c3d42',
    storageBucket: 'fir-c3d42.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1jGW6Emrn_AYUGjGzt6JBmcHiTShBK2s',
    appId: '1:495490506043:ios:a7c422d89117d72ddeeb1e',
    messagingSenderId: '495490506043',
    projectId: 'fir-c3d42',
    storageBucket: 'fir-c3d42.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNsfrBUpALKJyQ47bVWzV5K5MQ4wtyx0w',
    appId: '1:495490506043:web:e742bbb51e283957deeb1e',
    messagingSenderId: '495490506043',
    projectId: 'fir-c3d42',
    authDomain: 'fir-c3d42.firebaseapp.com',
    storageBucket: 'fir-c3d42.firebasestorage.app',
    measurementId: 'G-P6K9FGTM00',
  );
}
